### ISSUE TITLE
effect 

### ISSUE THREAD

**Issue by olieter** [Anders-Holst/xled_plus#4]
Just the effects with ctr work 

error 
  GlowCP(ctr).launch_movie()
TypeError: __init__() missing 1 required positional argument: 'cols'

**Comment by Anders-Holst** [comment]
If you check the code carefully you will see that GlowCP expects an additional argument. It is by design.

"CP" is my abbreviation for "ColorPicker". I am about to publish the color-picker any day now, and will then explain how to use the effects ending in "CP" (which all expects a list of HSL color specifications as their second argument).
